### ISSUE TITLE
Demo build doesn't work in Win 10

### ISSUE THREAD

**Issue by apereira435** [AshampooSystems/boden#32]
Try to run this command
`python ./boden.py -d open -t bodendemo`

got ...

```
[2020-04-23 14:18:47,043](bauerargparser): Bauer options: Namespace(accept_terms=False, arch=None, build_folder=None, build_system=None, cmake_option=None, command='open', config=None, debug=False, macos_min_version=None, macos_sdk_path=None, package_folder=None, package_generator=None, platform=None, target='bodendemo')
[2020-04-23 14:18:47,043](cmake): CMake found at: C:\Program Files\CMake\bin\cmake.exe
[2020-04-23 14:18:47,043](cmake): CMake found at: C:\Program Files\CMake\bin\cmake.exe
[2020-04-23 14:18:47,043](commandprocessor): Starting command: open
[2020-04-23 14:18:47,059](buildfolder): Existing configurations:
[2020-04-23 14:18:47,059](commandprocessor): Selected platform list:
[2020-04-23 14:18:47,059](commandprocessor): Defaulting to: android - AndroidStudio
[2020-04-23 14:18:47,059](commandprocessor): Build system does not match the one used when the projects for this platform were first prepared. Cleaning existing build files.
[2020-04-23 14:18:47,059](commandprocessor): (No previous state found)
[2020-04-23 14:18:47,059](commandprocessor): New config: BuildConfiguration(platform='android', arch='std', buildsystem='AndroidStudio', config=None)
[2020-04-23 14:18:47,293](commandprocessor): Preparing c:\code\projects\podlite\boden\build\android\std\AndroidStudio
[2020-04-23 14:18:47,293](androidexecutor): Preparing android environment...
[2020-04-23 14:18:47,293](androidexecutor): Ensuring that all necessary android packages are installed...
Warning: File C:\Users\André\.android\repositories.cfg could not be loaded.
Warning: File C:\Users\André\.android\repositories.cfg could not be loaded.
Warning: File C:\Users\André\.android\repositories.cfg could not be loaded.
[=======================================] 100% Computing updates...
[2020-04-23 14:18:53,927](androidexecutor): Done updating packages.
[2020-04-23 14:18:53,951](gradle): No system gradle found, using own...
[2020-04-23 14:18:53,953](gradle): Calling c:\code\projects\podlite\boden\3rdparty_build\gradle\gradle-5.3.1\bin\gradle.bat --stop
No Gradle daemons are running.
[2020-04-23 14:18:55,729](cmake): Server Protocol version: [1, 2]
[2020-04-23 14:18:55,744](cmake): VERSION: 3.17.1
[2020-04-23 14:18:55,744](androidexecutor): Starting configure ...
[2020-04-23 14:18:55,744](androidexecutor):  Arguments: ['-DCMAKE_TOOLCHAIN_FILE=C:/AndroidSdk/ndk-bundle/build/cmake/android.toolchain.cmake', '-DCMAKE_SYSTEM_NAME=Android', '-DANDROID_ABI=x86', '-DANDROID_NATIVE_API_LEVEL=28', '-DBAUER_RUN=Yes', '-DCMAKE_MAKE_PROGRAM=C:/AndroidSdk/ndk-bundle/prebuilt/windows-x86_64/bin/make.exe']
[2020-04-23 14:18:55,744](androidexecutor):  Generator: Unix Makefiles
[2020-04-23 14:18:55,744](cmake): Configuring ...
-- Check for working C compiler: C:/AndroidSdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Check for working C compiler: C:/AndroidSdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/AndroidSdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
-- Check for working CXX compiler: C:/AndroidSdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boden platform:
--   Name: android
--   Family: posix
-- Boden configuration:
--   Uses foundation kit: No
--   Uses java: Yes
--   Force shared: Yes
--   Force static: No
-- Found PythonInterp: C:/Python27/python.exe (found version "2.7.14")
-- Using the single-header code from C:/code/projects/podlite/boden/3rdparty/json/single_include/
-- CMake Warning (dev) at 3rdparty/googletest/CMakeLists.txt:3 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Boden library configuration:
--   Shared: Off
--   Architecture: 32 bit
-- Performing Test HAS_STD_FILESYSTEM
-- Performing Test HAS_STD_FILESYSTEM - Failed
-- Including custom std::filesystem implementation
-- Package name: boden-0.3.0-android-x86-28-%BUILD_TYPE%-Clang
-- Configuring done
-- CMake Deprecation Warning:
  The 'cmake-server(7)' is deprecated.  Please port clients to use the
  'cmake-file-api(7)' instead.


[2020-04-23 14:19:08,026](cmake): Done.
[2020-04-23 14:19:08,028](cmake): Generating ...
-- Generating done
[2020-04-23 14:19:10,055](cmake): Comparing: c:\code\projects\podlite\boden
[2020-04-23 14:19:10,055](cmake): with:     C:\code\projects\podlite\boden
[2020-04-23 14:19:10,055](cmake): with:     C:\code\projects\podlite\boden\3rdparty\googletest\googlemock
[2020-04-23 14:19:10,055](cmake): with:     C:\code\projects\podlite\boden\3rdparty\googletest
[2020-04-23 14:19:10,055](cmake): with:     C:\code\projects\podlite\boden\3rdparty\googletest\googletest
[2020-04-23 14:19:10,055](cmake): with:     C:\code\projects\podlite\boden\3rdparty\json
Traceback (most recent call last):
  File "c:\code\projects\podlite\boden\./bauer\bauer.py", line 71, in main
    return run(argv)
  File "c:\code\projects\podlite\boden\./bauer\bauer.py", line 67, in run
    commandProcessor.process()
  File "c:\code\projects\podlite\boden\./bauer\commandprocessor.py", line 119, in process
    self.prepare(configuration, platformState)
  File "c:\code\projects\podlite\boden\./bauer\commandprocessor.py", line 133, in prepare
    self.androidExecutor.prepare(platformState, configuration, self.args)
  File "c:\code\projects\podlite\boden\./bauer\androidexecutor.py", line 113, in prepare
    self.prepareAndroidStudio(platformState, configuration, androidAbi, androidHome, buildDir, args)
  File "c:\code\projects\podlite\boden\./bauer\androidexecutor.py", line 207, in prepareAndroidStudio
    project = config["main-project"]
KeyError: 'main-project'
```
I had also another problem the build was pointing to `windows-x86_64` folder but on the new ndk it is just `windows`

**Comment by gitoby** [comment]
Thanks for reporting. We'll have a look once we have some time left.
