### ISSUE TITLE
Installing and running test demo

### ISSUE THREAD

**Issue by flower78** [AshampooSystems/boden#43]
Dear Boden Team,

I installed all dependencies and tryed running the demo via `python boden.py open -p android -t bodendemo` . 

I got the following response: 
`Traceback (most recent call last):
  File "C:\Users\DR\Documents\boden\./bauer\bauer.py", line 71, in main
    return run(argv)
  File "C:\Users\DR\Documents\boden\./bauer\bauer.py", line 37, in run
    generatorInfo = GeneratorInfo();
  File "C:\Users\DR\Documents\boden\./bauer\generatorinfo.py", line 23, in __init__
    cmakeHelp = subprocess.check_output("\"" + self.cmakeExecutable + "\" --help", shell=True, universal_newlines=True, stderr=errOutFile );
  File "C:\Program Files\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\Python310\lib\subprocess.py", line 503, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "C:\Program Files\Python310\lib\subprocess.py", line 1136, in communicate
    stdout = self.stdout.read()
  File "C:\Program Files\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3: character maps to <undefined>`

Has anyone else run into this? Any possible solution??

**Comment by Mamograg17** [comment]
I think the project has been left, there is no response anymore, we hope the developer will continue in the future.
