### ISSUE TITLE
Cmake Issue

### ISSUE THREAD

**Issue by yakupcemilk** [AshampooSystems/boden#47]
I've downloaded the Cmake but when I tried to run demo project of Boden Framework, it shows an error:

>C:\Users\yakup.kayabas\boden>python boden.py open -p android -t bodendemo 
>Traceback (most recent call last):
>  File "C:\Users\yakup.kayabas\boden\./bauer\bauer.py", line 71, in main
>    return run(argv)
>           ^^^^^^^^^
>  File "C:\Users\yakup.kayabas\boden\./bauer\bauer.py", line 37, in run
>    generatorInfo = GeneratorInfo();
>                    ^^^^^^^^^^^^^^^
>  File "C:\Users\yakup.kayabas\boden\./bauer\generatorinfo.py", line 11, in __init__
>    raise Exception("Couldn't find cmake executable. Please download and install it from www.cmake.org/download")
>Exception: Couldn't find cmake executable. Please download and install it from 'www.cmake.org/download'

but like I said, I've downloaded and double checked the Cmake and Cmake's version that I have.

**Comment by yakupcemilk** [comment]
I'll try to solve it. When I solve and figure it why is that happened, I'll write that down.
