### ISSUE TITLE
Build is not working on macOS Mojave 10.14.5 (18F132)

### ISSUE THREAD

**Issue by valduze** [AshampooSystems/boden#5]
Hi guys,
When I run:
$ python boden.py open

I get this error:
[2019-05-30 22:02:56,335] Defaulting to: ios - Xcode
[2019-05-30 22:02:56,335] Build system does not match the one used when the projects for this platform were first prepared. Cleaning existing build files.
[2019-05-30 22:02:56,336] Preparing /Users/myusername/projects/games/boden/build/ios/std/Xcode

2019-05-30 22:02:56,352] Configuring ...
-- CMake Error:
  Xcode 1.5 not supported.

Traceback (most recent call last):
  File "/Users/myusername/projects/games/boden/./bauer/bauer.py", line 66, in main
    return run(argv)
  File "/Users/myusername/projects/games/boden/./bauer/bauer.py", line 62, in run
    commandProcessor.process()
  File "/Users/myusername/projects/games/boden/./bauer/commandprocessor.py", line 119, in process
    self.prepare(configuration, platformState)
  File "/Users/myusername/projects/games/boden/./bauer/commandprocessor.py", line 135, in prepare
    self.buildExecutor.prepare(platformState, configuration, self.args)
  File "/Users/myusername/projects/games/boden/./bauer/buildexecutor.py", line 155, in prepare
    self.cmake.configure(cmakeArguments)
  File "/Users/myusername/projects/games/boden/./bauer/cmake.py", line 92, in configure
    self.waitForResult("configure", "CONFIGURE")
  File "/Users/myusername/projects/games/boden/./bauer/cmake.py", line 83, in waitForResult
    raise Exception("Error occured during configure:", payload["errorMessage"])
Exception: ('Error occured during configure:', u'Could not set up the requested combination of "generator" and "extraGenerator"')

I am really looking forward to play on this.
Thanks,
Jongi

**Comment by gitoby** [comment]
Hi Jongi,

@Maddimax is our build system expert. He can probably give you a better answer later, but I'll try to help you out meanwhile.

It looks as if CMake is not able to find your Xcode installation. Which version of Xcode are you using?

Please try the following:

* Remove the build folder: `rm -rf build` within your local Boden working tree. Then try again.
* Check if Xcode (10.1 or later) is installed properly in the default location (/Applications/Xcode) and command line tools have been installed.

A similar CMake error has been reported with other libraries for users who have multiple Xcode installs. In that case it seems to help to run `xcode-select --switch <PATH_TO_XCODE_APP>`.

Hope this helps! Let me know if the issue persists.

Tobias

**Comment by Maddimax** [comment]
@valduze Did @gitoby's information help? 

- Marcus
